DROP DATABASE DataBaseRestaurante;

CREATE DATABASE DataBaseRestaurante;
use DataBaseRestaurante;


/*Parte de Empleados*/
 CREATE TABLE IF NOT EXISTS EmpleadoSalarioRango(
  USERTYPE INT NOT NULL,
  USERSALARIOMIN DECIMAL(10,2) NOT NULL,
  USERSALARIOMAX DECIMAL(10,2) NOT NULL,
  CONSTRAINT emplTypeRangoKey primary key (USERTYPE),
  CONSTRAINT rangoMinMaxSalario CHECK (USERSALARIOMAX >= USERSALARIOMIN)
 );

CREATE TABLE IF NOT EXISTS UsersEmpl(
 USERNAME VARCHAR(30) 	NOT NULL,
 USERPASSWORD VARCHAR(15) NOT NULL,
 USERTYPE INT NOT NULL,
 USERSALARIO DECIMAL(10,2) NOT NULL, #Salario 
 CONSTRAINT userEmplNameKey primary key (USERNAME),
 CONSTRAINT userEmplTypeUni UNIQUE (USERNAME, USERTYPE),
 CONSTRAINT userEmplTypeRang FOREIGN KEY(USERTYPE) REFERENCES EmpleadoSalarioRango(USERTYPE) ON DELETE CASCADE ON UPDATE CASCADE
 );
 

 
 
/*Sucursal */
CREATE TABLE IF NOT EXISTS Sucursal(
  IDSUCURSAL VARCHAR(10) NOT NULL,
  GERENTE VARCHAR(30) NOT NULL,
  
  CONSTRAINT idSucursalKey PRIMARY KEY (IDSUCURSAL),
  CONSTRAINT idGerente FOREIGN KEY(GERENTE) REFERENCES UsersEmpl(USERNAME) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS SucursalEmpleados(
  IDSUCURSAL VARCHAR(10) NOT NULL,
  USERNAME VARCHAR(30) NOT NULL,
  
  CONSTRAINT userEmpleadoSucursal PRIMARY KEY (IDSUCURSAL, USERNAME),
  CONSTRAINT sucursalEmplForeKey FOREIGN KEY(IDSUCURSAL) REFERENCES Sucursal(IDSUCURSAL) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT emplSucursalForeKey FOREIGN KEY(USERNAME) REFERENCES UsersEmpl(USERNAME) ON DELETE CASCADE ON UPDATE CASCADE
);



 
 /*Productos y Menú*/
 
 CREATE TABLE IF NOT EXISTS Menu(
   IDMENU INT AUTO_INCREMENT,
   CONSTRAINT idMenu primary key (IDMENU)
 );
 
 CREATE TABLE IF NOT EXISTS Combo(
   IDCOMBO INT AUTO_INCREMENT,
   NOMBRE VARCHAR(30) NOT NULL,
   ACTIVO BOOLEAN NOT NULL,
   PRECIO DECIMAL(10,2) NOT NULL,
   DESCRIPCION VARCHAR(50) NOT NULL,
   CONSTRAINT idComboKey primary key (IDCOMBO),
   CONSTRAINT nameCombokey unique (NOMBRE)
 );
 
 CREATE TABLE IF NOT EXISTS Producto(
   IDPRODUCTO INT AUTO_INCREMENT,
   NOMBRE VARCHAR(30) NOT NULL,
   ACTIVO BOOLEAN NOT NULL,
   PRECIO DECIMAL(10,2) NOT NULL,
   DESCRIPCION VARCHAR(50) NOT NULL,
   TIEMPO INT NOT NULL,
   CONSTRAINT idProductoKey primary key (IDPRODUCTO),
   CONSTRAINT nameProduckey unique (NOMBRE)
 );
 
 
 CREATE TABLE IF NOT EXISTS ComboProducto(
   IDCOMBO INT NOT NULL,
   IDPRODUCTO INT NOT NULL,
   CANT INT NOT NULL, #Cuantos productos de este tipo hay en ese combo
   CONSTRAINT idComboProdKey primary key (IDCOMBO, IDPRODUCTO),
   CONSTRAINT idComProductoKey FOREIGN KEY(IDCOMBO) REFERENCES Combo(IDCOMBO) ON DELETE CASCADE ON UPDATE CASCADE,
   CONSTRAINT idProComboKey FOREIGN KEY(IDPRODUCTO) REFERENCES Producto(IDPRODUCTO) ON DELETE CASCADE ON UPDATE CASCADE
 );
 
  CREATE TABLE IF NOT EXISTS ComboMenu(
   IDMENU INT NOT NULL,
   IDCOMBO INT NOT NULL,
   CONSTRAINT idComboMenuKey primary key (IDMENU, IDCOMBO),
   CONSTRAINT idMenuComboKey FOREIGN KEY(IDMENU) REFERENCES Menu(IDMENU) ON DELETE CASCADE ON UPDATE CASCADE,
   CONSTRAINT idCombMenuKey FOREIGN KEY(IDCOMBO) REFERENCES Combo(IDCOMBO) ON DELETE CASCADE ON UPDATE CASCADE
 );
 
  CREATE TABLE IF NOT EXISTS ProductMenu(
   IDMENU INT NOT NULL,
   IDPRODUCTO INT NOT NULL,
   CONSTRAINT idProductMenuKey primary key (IDMENU, IDPRODUCTO),
   CONSTRAINT idMenuProductKey FOREIGN KEY(IDMENU) REFERENCES Menu(IDMENU) ON DELETE CASCADE ON UPDATE CASCADE,
   CONSTRAINT idProducMenuKey FOREIGN KEY(IDPRODUCTO) REFERENCES Producto(IDPRODUCTO) ON DELETE CASCADE ON UPDATE CASCADE
 );


 /* Parte del Cliente */
CREATE TABLE IF NOT EXISTS UsersClient(
 USERNAME VARCHAR(30) 	NOT NULL,
 USERPASSWORD VARCHAR(15) NOT NULL,
 USERTYPE INT NOT NULL DEFAULT 0,
 CONSTRAINT userClientNameKey primary key (USERNAME)
 );
 
 #El pedido 
 CREATE TABLE IF NOT exists Pedido(
 IDPEDIDO INT AUTO_INCREMENT,
 IDSUCURSAL VARCHAR(10) NOT NULL,
 TYPEPEDIDO INT NOT NULL,
 TYPEPAGO INT NOT NULL,
 TOTAL DECIMAL(10,2) NOT NULL,
 ENTREGADO BOOLEAN NOT NULL,
 FECHA DATE NOT NULL,
 CONSTRAINT idPedidoKey PRIMARY KEY (IDPEDIDO,IDSUCURSAL),
 CONSTRAINT sucurPediForeKey FOREIGN KEY(IDSUCURSAL) REFERENCES Sucursal(IDSUCURSAL) ON DELETE CASCADE ON UPDATE CASCADE
 
 );
 #Los combos que van en el pedido
  CREATE TABLE IF NOT EXISTS ComboPedido(
   IDPEDIDO INT NOT NULL,
   IDCOMBO INT NOT NULL,
   CANTIDAD INT NOT NULL,
   CONSTRAINT idComboMenuKey primary key (IDPEDIDO, IDCOMBO),
   CONSTRAINT idPedidoComboKey FOREIGN KEY(IDPEDIDO) REFERENCES Pedido(IDPEDIDO) ON DELETE CASCADE ON UPDATE CASCADE,
   CONSTRAINT idCombPedidoKey FOREIGN KEY(IDCOMBO) REFERENCES Combo(IDCOMBO) ON DELETE CASCADE ON UPDATE CASCADE
 );
 #Los productos que van en el pedido
  CREATE TABLE IF NOT EXISTS ProductPedido(
   IDPEDIDO INT NOT NULL,
   IDPRODUCTO INT NOT NULL,
   CANTIDAD INT NOT NULL,
   CONSTRAINT idProductPedidoKey primary key (IDPEDIDO, IDPRODUCTO),
   CONSTRAINT idPedidoProductKey FOREIGN KEY(IDPEDIDO) REFERENCES Pedido(IDPEDIDO) ON DELETE CASCADE ON UPDATE CASCADE,
   CONSTRAINT idProducPedidoKey FOREIGN KEY(IDPRODUCTO) REFERENCES Producto(IDPRODUCTO) ON DELETE CASCADE ON UPDATE CASCADE
 );
 
 #Pedido Express
  CREATE TABLE IF NOT exists PedidoExpr(
 IDPEDIDO INT NOT NULL,
 USERNAMECLI VARCHAR(30) NOT NULL,
 USERNAMEREP VARCHAR(30) NOT NULL,
 TIEMPOENTREGA TIME NOT NULL,
 TIEMPOPREPARACION TIME NOT NULL,
 PUNTUACION INT NOT NULL,
 CONSTRAINT idPedidoExpKey PRIMARY KEY (IDPEDIDO),
 CONSTRAINT idPedidoExpForKey FOREIGN KEY(IDPEDIDO) REFERENCES Pedido(IDPEDIDO) ON DELETE CASCADE ON UPDATE CASCADE,

 CONSTRAINT userClienPedidoExp foreign key (USERNAMECLI) REFERENCES UsersClient(USERNAME) ON DELETE CASCADE ON UPDATE CASCADE,
 CONSTRAINT userRepartPedidoExp foreign key (USERNAMEREP) REFERENCES UsersEmpl(USERNAME) ON DELETE CASCADE ON UPDATE CASCADE 
 );
 
  #Pedido Express más bien orden
  CREATE TABLE IF NOT exists PedidoLocal(
 IDPEDIDO INT NOT NULL,
 USERNAMESALON VARCHAR(30) NOT NULL,
 
 CONSTRAINT idPedidoLocKey PRIMARY KEY (IDPEDIDO),
 CONSTRAINT idPedidoLocForKey FOREIGN KEY(IDPEDIDO) REFERENCES Pedido(IDPEDIDO) ON DELETE CASCADE ON UPDATE CASCADE,
 CONSTRAINT userSaloneroPedidoExp foreign key (USERNAMESALON ) REFERENCES UsersEmpl(USERNAME) ON DELETE CASCADE ON UPDATE CASCADE 
 );
 
 

 
 
 