USE  DataBaseRestaurante;
CREATE USER 'userconect'@'%' IDENTIFIED BY 'userconect';	
GRANT ALL PRIVILEGES ON  DataBaseRestaurante.* TO 'userconect'@'%';

DELIMITER //
CREATE PROCEDURE `raise`(`errno` BIGINT UNSIGNED, `message` VARCHAR(256))
BEGIN
SIGNAL SQLSTATE
    'ERR0R'
SET
    MESSAGE_TEXT = `message`,
    MYSQL_ERRNO = `errno`;
END //
DELIMITER ;

DELIMITER //
#Agregar Usuarios
CREATE PROCEDURE ADDNEWUSERCLIENT(IN IN_USERNAME VARCHAR(20), 
                            IN IN_USERPASSWORD VARCHAR(15))
BEGIN
    DECLARE CONT INTEGER DEFAULT 0;
	
	SELECT COUNT(USERNAME)
	INTO CONT
	FROM UsersEmpl
	WHERE IN_USERNAME = USERNAME;
    
    IF(CONT = 0) THEN 
		INSERT INTO UsersClient(USERNAME,USERPASSWORD)
		VALUES(IN_USERNAME, IN_USERPASSWORD);
	ELSE 
       call `raise`(0001, 'Usuario ya existene');
    END IF;
END //
DELIMITER ;


call ADDNEWUSERCLIENT("jose","1234");


CREATE PROCEDURE ADDNEWUSEREMPL(IN IN_USERNAME VARCHAR(20), 
                            IN IN_USERPASSWORD VARCHAR(15))
BEGIN
     #HAY QUE HACERLO, AUN FALTA 
END //
DELIMITER ;

DELIMITER //
#VERIFICAR LOGIN
CREATE PROCEDURE LOGINUSER(IN IN_USERNAME VARCHAR(20), 
						   IN IN_USERPASSWORD VARCHAR(15),
						   OUT IN_TYPEUSER INT)
BEGIN
    DECLARE CONT INTEGER DEFAULT 0;
	
	SELECT COUNT(USERNAME),USERTYPE
	INTO CONT,IN_TYPEUSER
	FROM UsersClient 
	WHERE IN_USERNAME = USERNAME AND IN_USERPASSWORD = USERPASSWORD;
    
    IF(CONT = 0) THEN 
		SELECT COUNT(USERNAME),USERTYPE
	    INTO CONT,IN_TYPEUSER
	    FROM UsersEmpl 
	    WHERE IN_USERNAME = USERNAME AND IN_USERPASSWORD = USERPASSWORD;
        IF(CONT = 0) THEN
         SET IN_TYPEUSER := -1;
		END IF;
    END IF;
    
END //
DELIMITER ;

DELIMITER //
#GET USUARIOS
CREATE PROCEDURE GETUSERS()
BEGIN
	SELECT USERNAME, USERPASSWORD,USERTYPE
	FROM UsersEmpl
    UNION
    SELECT USERNAME, USERPASSWORD,USERTYPE
    FROM UsersClient;
END //
DELIMITER ;



