USE  DataBaseRestaurante;
CREATE USER 'userconect'@'%' IDENTIFIED BY 'userconect';	
GRANT ALL PRIVILEGES ON  DataBaseRestaurante.* TO 'userconect'@'%';

DELIMITER //
#Agregar Usuarios
CREATE PROCEDURE ADDNEWUSERCLIENT(IN IN_USERNAME VARCHAR(20), 
                            IN IN_USERPASSWORD VARCHAR(15))
BEGIN
    INSERT INTO UsersClient(USERNAME,USERPASSWORD)
    VALUES(IN_USERNAME, IN_USERPASSWORD);
END //

call ADDNEWUSERCLIENT("jose","1234");
select * from UsersClient

CREATE PROCEDURE ADDNEWUSEREMPL(IN IN_USERNAME VARCHAR(20), 
                            IN IN_USERPASSWORD VARCHAR(15))
BEGIN
    INSERT INTO UsersClient(USERNAME,USERPASSWORD)
    VALUES(IN_USERNAME, IN_USERPASSWORD);
END //


DELIMITER //
#VERIFICAR LOGIN
CREATE PROCEDURE LOGINUSER(IN IN_USERNAME VARCHAR(20), 
						   IN IN_USERPASSWORD VARCHAR(15),
						   OUT IN_TYPEUSER INT)
BEGIN
    DECLARE CONT INTEGER DEFAULT 0;
	
	SELECT COUNT(USERNAME),USERTYPE
	INTO CONT,IN_TYPEUSER
	FROM UsersClient 
	WHERE IN_USERNAME = USERNAME AND IN_USERPASSWORD = USERPASSWORD;
    
    IF(CONT = 0) THEN 
		SELECT COUNT(USERNAME),USERTYPE
	    INTO CONT,IN_TYPEUSER
	    FROM UsersEmpl 
	    WHERE IN_USERNAME = USERNAME AND IN_USERPASSWORD = USERPASSWORD;
        IF(CONT = 0) THEN
         SET IN_TYPEUSER := -1;
		END IF;
    END IF;
    
END //
DELIMITER ;