USE  DataBaseRestaurante;
CREATE USER 'userconect'@'%' IDENTIFIED BY 'userconect';	
GRANT ALL PRIVILEGES ON  DataBaseRestaurante.* TO 'userconect'@'%';

DELIMITER //
CREATE PROCEDURE `raise`(`errno` BIGINT UNSIGNED, `message` VARCHAR(256))
BEGIN
SIGNAL SQLSTATE
    'ERR0R'
SET
    MESSAGE_TEXT = `message`,
    MYSQL_ERRNO = `errno`;
END //
DELIMITER ;



DELIMITER //
#Agregar Usuarios
CREATE PROCEDURE ADDNEWUSERCLIENT(IN IN_USERNAME VARCHAR(20), 
                            IN IN_USERPASSWORD VARCHAR(15))
BEGIN
    DECLARE CONT INTEGER DEFAULT 0;
	
	SELECT COUNT(USERNAME)
	INTO CONT
	FROM UsersEmpl
	WHERE IN_USERNAME = USERNAME;
    
    IF(CONT = 0) THEN 
		INSERT INTO UsersClient(USERNAME,USERPASSWORD)
		VALUES(IN_USERNAME, IN_USERPASSWORD);
	ELSE 
       call `raise`(0001, 'Usuario ya existente');
    END IF;
END //
DELIMITER ;


call ADDNEWUSERCLIENT("jose","1234");
call ADDNEWUSERCLIENT("dani","1234");
call ADDNEWUSERCLIENT("roberto","1234");
call ADDNEWUSERCLIENT("gabriel","1234");

DELIMITER //
#Agregar rango tipo

CREATE PROCEDURE ADDNEWRANGOTIPO(IN IN_USERTYPE INT, 
                            IN IN_USERSALARIOMIN DECIMAL(10,2),
                            IN IN_USERSALARIOMAX DECIMAL(10,2))
BEGIN
   IF(IN_USERSALARIOMIN <= IN_USERSALARIOMAX) THEN
	INSERT INTO EmpleadoSalarioRango(USERTYPE, USERSALARIOMIN, USERSALARIOMAX)
	VALUES(IN_USERTYPE, IN_USERSALARIOMIN, IN_USERSALARIOMAX);
   else
     call `raise`(0002, 'El salario MINIMO debe ser <= al MAXIMO');
   END IF;
END //
DELIMITER ;

call ADDNEWRANGOTIPO(31, 30000,50000);


DELIMITER //
CREATE PROCEDURE ADDNEWUSEREMPL(IN IN_USERNAME VARCHAR(30), 
                            IN IN_USERPASSWORD VARCHAR(15),
                            IN IN_USERTYPE INT,
                            IN IN_USERSALARIO DECIMAL(10,2))
BEGIN
    DECLARE CONT INTEGER DEFAULT 0;
    DECLARE RANGO INT DEFAULT -1;
	SELECT COUNT(USERNAME)
	INTO CONT
	FROM UsersClient
	WHERE IN_USERNAME = USERNAME;
    
    IF(CONT = 0) THEN
		SELECT COUNT(USERTYPE) 
        INTO RANGO
        FROM EmpleadoSalarioRango
        WHERE USERTYPE = IN_USERTYPE AND (IN_USERSALARIO > USERSALARIOMIN - 1)
									AND (IN_USERSALARIO < USERSALARIOMAX + 1);
        IF(RANGO = 1) THEN
		  INSERT INTO UsersEmpl(USERNAME,USERPASSWORD,USERTYPE,USERSALARIO)
		  VALUES(IN_USERNAME,IN_USERPASSWORD,IN_USERTYPE,IN_USERSALARIO);
        ELSE 
          call `raise`(0002, 'El salario no es correspondiente al rango.');
        END IF;
	ELSE 
       call `raise`(0001, 'Usuario ya existente');
    END IF;
END //
DELIMITER ;
call ADDNEWUSEREMPL("empl","1234",31,50000);

DELIMITER //
#VERIFICAR LOGIN
CREATE PROCEDURE LOGINUSER(IN IN_USERNAME VARCHAR(20), 
						   IN IN_USERPASSWORD VARCHAR(15),
						   OUT IN_TYPEUSER INT)
BEGIN
    DECLARE CONT INTEGER DEFAULT 0;
	
	SELECT COUNT(USERNAME),USERTYPE
	INTO CONT,IN_TYPEUSER
	FROM UsersClient 
	WHERE IN_USERNAME = USERNAME AND IN_USERPASSWORD = USERPASSWORD;
    
    IF(CONT = 0) THEN 
		SELECT COUNT(USERNAME),USERTYPE
	    INTO CONT,IN_TYPEUSER
	    FROM UsersEmpl 
	    WHERE IN_USERNAME = USERNAME AND IN_USERPASSWORD = USERPASSWORD;
        IF(CONT = 0) THEN
         SET IN_TYPEUSER := -1;
		END IF;
    END IF;
    
END //
DELIMITER ;

DELIMITER //
#GET USUARIOS
CREATE PROCEDURE GETUSERS()
BEGIN
	SELECT USERNAME, USERPASSWORD,USERTYPE
	FROM UsersEmpl
    UNION
    SELECT USERNAME, USERPASSWORD,USERTYPE
    FROM UsersClient;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE GETPRODUCTOS()
BEGIN
	SELECT *
    FROM Producto;
END //
DELIMITER ;

DELIMITER //
#Agregar PRODUCTO
CREATE PROCEDURE ADDNEWPRODUCTO(IN IN_NOMBRE VARCHAR(30), 
                            IN IN_ACTIVO BOOLEAN,
                            IN IN_PRECIO DECIMAL(10,2),
                            IN IN_DESCRIPCION VARCHAR(50))
BEGIN
	INSERT INTO Producto(NOMBRE,ACTIVO, PRECIO, DESCRIPCION)
	VALUES(IN_NOMBRE, IN_ACTIVO, IN_PRECIO, IN_DESCRIPCION);
END //
DELIMITER ;

DELIMITER //
#Agregar PRODUCTO
CREATE PROCEDURE SETDISPPRODUCTO(IN IN_NOMBRE VARCHAR(30), 
                            IN IN_ACTIVO BOOLEAN)
BEGIN
	UPDATE Producto
    SET ACTIVO = IN_ACTIVO
    WHERE NOMBRE = IN_NOMBRE;
END //
DELIMITER ;



call addnewproducto("Coca-Cola",false,700,"Refrescante bebida carbonatada.");
call setdispproducto("Coca-Cola", true);

DELIMITER //
CREATE PROCEDURE GETCOMBOS()
BEGIN
	SELECT *
    FROM Combo;
END //
DELIMITER ;

DELIMITER //
#Agregar PRODUCTO
CREATE PROCEDURE ADDNEWCOMBO(IN IN_NOMBRE VARCHAR(30), 
                            IN IN_ACTIVO BOOLEAN,
                            IN IN_PRECIO DECIMAL(10,2),
                            IN IN_DESCRIPCION VARCHAR(50))
BEGIN
	INSERT INTO Combo(NOMBRE,ACTIVO, PRECIO, DESCRIPCION)
	VALUES(IN_NOMBRE, IN_ACTIVO, IN_PRECIO, IN_DESCRIPCION);
END //
DELIMITER ;

DELIMITER //
#Agregar PRODUCTO
CREATE PROCEDURE SETDISCOMBO(IN IN_NOMBRE VARCHAR(30), 
                            IN IN_ACTIVO BOOLEAN)
BEGIN
	UPDATE Combo
    SET ACTIVO = IN_ACTIVO
    WHERE NOMBRE = IN_NOMBRE;
END //
DELIMITER ;

#getProductosCombo
DELIMITER //
CREATE PROCEDURE GETCOMBOPRODUCTO(IN IN_NOMBRE VARCHAR(30))
BEGIN
	SELECT p.IDPRODUCTO, p.NOMBRE, p.ACTIVO, p.PRECIO, p.DESCRIPCION, cp.CANT  
    FROM Producto AS p INNER JOIN 
         ComboProducto AS cp ON (cp.IDPRODUCTO = p.IDPRODUCTO)  INNER JOIN
         Combo AS c ON (cp.IDCOMBO = c.IDCOMBO)
    WHERE c.NOMBRE = IN_NOMBRE;
END //
DELIMITER ;

#getProductosCombo
DELIMITER //
CREATE PROCEDURE SETCOMBOPRODUCTO(IN IN_NOMBRECOM VARCHAR(30), IN IN_NOMBREPRO VARCHAR(30), IN CANTIDAD INT)
BEGIN
    DECLARE VAR_IDCOMBO INT;
    DECLARE VAR_IDPRODUCTO INT;
    
    SELECT IDPRODUCTO
    INTO VAR_IDPRODUCTO
    FROM PRODUCTO 
    WHERE NOMBRE = IN_NOMBREPRO;
    
    SELECT IDCOMBO
    INTO VAR_IDCOMBO
    FROM COMBO
    WHERE NOMBRE = IN_NOMBRECOM;
    
	INSERT INTO ComboProducto(IDCOMBO,IDPRODUCTO,CANT)
	VALUES(VAR_IDCOMBO, VAR_IDPRODUCTO, CANTIDAD);

END //
DELIMITER ;


call addnewcombo("Pobre",false,3500,"Combo para universitarios.");
call getcombos();
call setdiscombo("Pobre",true);
call SETCOMBOPRODUCTO("Pobre","Coca-Cola",2);





