/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Controlador;
import Model.Producto;
import Model.UserClient;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author danip
 */
public class AgregarProducto extends javax.swing.JFrame {

    /**
     * Creates new form AgregarProducto
     */
    public AgregarProducto() {
        initComponents();
        setIconImage(getIconImage());
        this.setLocationRelativeTo(null);
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Resources/icons2.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTNombre = new javax.swing.JTextField();
        jTDescripcion = new javax.swing.JTextField();
        jLTitulo = new javax.swing.JLabel();
        jBConfirmacion = new javax.swing.JButton();
        jBInicio = new javax.swing.JButton();
        jLNombre1 = new javax.swing.JLabel();
        jLNombre2 = new javax.swing.JLabel();
        jLNombre3 = new javax.swing.JLabel();
        jLNombre4 = new javax.swing.JLabel();
        jSpinnerPrecio = new javax.swing.JSpinner();
        jSpinnerDuracion = new javax.swing.JSpinner();
        shadowTable = new javax.swing.JLabel();
        jLImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(760, 505));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTNombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 250, 30));

        jTDescripcion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 250, 30));

        jLTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(241, 234, 226));
        jLTitulo.setText("Agregar Producto");
        getContentPane().add(jLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 80, 360, -1));

        jBConfirmacion.setBackground(new java.awt.Color(241, 234, 226));
        jBConfirmacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBConfirmacion.setForeground(new java.awt.Color(89, 17, 18));
        jBConfirmacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/checked2.png"))); // NOI18N
        jBConfirmacion.setText("Crear");
        jBConfirmacion.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jBConfirmacion.setOpaque(false);
        jBConfirmacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfirmacionActionPerformed(evt);
            }
        });
        getContentPane().add(jBConfirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 250, 40));

        jBInicio.setBackground(new java.awt.Color(241, 234, 226));
        jBInicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBInicio.setForeground(new java.awt.Color(89, 17, 18));
        jBInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/menuPrin.png"))); // NOI18N
        jBInicio.setText("Inicio");
        jBInicio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jBInicio.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jBInicio.setMaximumSize(new java.awt.Dimension(130, 40));
        jBInicio.setMinimumSize(new java.awt.Dimension(130, 40));
        jBInicio.setOpaque(false);
        jBInicio.setPreferredSize(new java.awt.Dimension(130, 40));
        jBInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInicioActionPerformed(evt);
            }
        });
        getContentPane().add(jBInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 140, -1));

        jLNombre1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLNombre1.setForeground(new java.awt.Color(241, 234, 226));
        jLNombre1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLNombre1.setText("Descripcion:");
        getContentPane().add(jLNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 230, -1));

        jLNombre2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLNombre2.setForeground(new java.awt.Color(241, 234, 226));
        jLNombre2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLNombre2.setText("Nombre:");
        getContentPane().add(jLNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 230, -1));

        jLNombre3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLNombre3.setForeground(new java.awt.Color(241, 234, 226));
        jLNombre3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLNombre3.setText("Precio:");
        getContentPane().add(jLNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 230, -1));

        jLNombre4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLNombre4.setForeground(new java.awt.Color(241, 234, 226));
        jLNombre4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLNombre4.setText("Duracion:");
        getContentPane().add(jLNombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 230, -1));

        jSpinnerPrecio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jSpinnerPrecio.setModel(new javax.swing.SpinnerNumberModel(2000.0d, 1.0d, null, 1.0d));
        getContentPane().add(jSpinnerPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 250, 30));

        jSpinnerDuracion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jSpinnerDuracion.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        getContentPane().add(jSpinnerDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 250, 30));

        shadowTable.setBackground(new java.awt.Color(152, 50, 39));
        shadowTable.setOpaque(true);
        getContentPane().add(shadowTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 570, 440));

        jLImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/vinoConBlanco.jpg"))); // NOI18N
        jLImagen.setText("jLabel1");
        jLImagen.setMaximumSize(new java.awt.Dimension(760, 505));
        jLImagen.setMinimumSize(new java.awt.Dimension(760, 505));
        jLImagen.setPreferredSize(new java.awt.Dimension(760, 505));
        getContentPane().add(jLImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInicioActionPerformed
        // TODO add your handling code here:
        Principal p = Controlador.getCtr().getPrincipal();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBInicioActionPerformed

    private void jBConfirmacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmacionActionPerformed
        // TODO add your handling code here:
        addProducto();
    }//GEN-LAST:event_jBConfirmacionActionPerformed

    private void addProducto(){
        if(validarCampos()){
          String mensaje = Controlador.getCtr().setNewProducto(
          new Producto(0,this.jTNombre.getText(),this.jTDescripcion.getText(),(double)this.jSpinnerPrecio.getValue(),
                        false,(int)this.jSpinnerDuracion.getValue()));
          Controlador.getCtr().setProductosArray();
          
          JOptionPane.showMessageDialog(null,mensaje);
          limpiarCampos();
        }else{
          JOptionPane.showMessageDialog(null, "Llene los datos correspondientes");
        }

    }
    
    private void limpiarCampos(){
         this.jTNombre.setText("");
         this.jTDescripcion.setText("");
    }
    
    private boolean validarCampos(){
        boolean result = true;
        if(this.jTNombre.getText().isEmpty() || this.jTDescripcion.getText().isEmpty())
            result = false;
        return result;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarProducto().setVisible(true);
            }
        }); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConfirmacion;
    private javax.swing.JButton jBInicio;
    private javax.swing.JLabel jLImagen;
    private javax.swing.JLabel jLNombre1;
    private javax.swing.JLabel jLNombre2;
    private javax.swing.JLabel jLNombre3;
    private javax.swing.JLabel jLNombre4;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JSpinner jSpinnerDuracion;
    private javax.swing.JSpinner jSpinnerPrecio;
    private javax.swing.JTextField jTDescripcion;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JLabel shadowTable;
    // End of variables declaration//GEN-END:variables
}
