/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Controlador;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author danip
 */
public class IniciarSesion extends javax.swing.JFrame {

    /**
     * Creates new form IniciarSesion
     */
    public IniciarSesion() {
        initComponents();
        setIconImage(getIconImage());
        this.setLocationRelativeTo(null);
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Resources/icons2.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBInicio = new javax.swing.JButton();
        jLConfirmar = new javax.swing.JButton();
        jLTitulo = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jLContrasena = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jtContrasena = new javax.swing.JTextField();
        jLImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(760, 505));
        setMinimumSize(new java.awt.Dimension(760, 505));
        setPreferredSize(new java.awt.Dimension(760, 505));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBInicio.setBackground(new java.awt.Color(241, 234, 226));
        jBInicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBInicio.setForeground(new java.awt.Color(89, 17, 18));
        jBInicio.setText("Inicio");
        jBInicio.setMaximumSize(new java.awt.Dimension(130, 40));
        jBInicio.setMinimumSize(new java.awt.Dimension(130, 40));
        jBInicio.setPreferredSize(new java.awt.Dimension(130, 40));
        jBInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInicioActionPerformed(evt);
            }
        });
        getContentPane().add(jBInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, -1, -1));

        jLConfirmar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLConfirmar.setForeground(new java.awt.Color(89, 17, 18));
        jLConfirmar.setText("Confirmar");
        jLConfirmar.setMaximumSize(new java.awt.Dimension(130, 40));
        jLConfirmar.setMinimumSize(new java.awt.Dimension(130, 40));
        jLConfirmar.setPreferredSize(new java.awt.Dimension(130, 40));
        getContentPane().add(jLConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, -1, -1));

        jLTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(241, 234, 226));
        jLTitulo.setText("Iniciar Sesion");
        getContentPane().add(jLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        jLNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(241, 234, 226));
        jLNombre.setText("Nombre");
        getContentPane().add(jLNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        jLContrasena.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLContrasena.setForeground(new java.awt.Color(241, 234, 226));
        jLContrasena.setText("Contrseña");
        getContentPane().add(jLContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, -1));

        jTNombre.setBackground(new java.awt.Color(241, 234, 226));
        getContentPane().add(jTNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 180, -1));

        jtContrasena.setBackground(new java.awt.Color(241, 234, 226));
        jtContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtContrasenaActionPerformed(evt);
            }
        });
        getContentPane().add(jtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 170, -1));

        jLImagen.setBackground(new java.awt.Color(241, 234, 226));
        jLImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/vinoConBlanco.jpg"))); // NOI18N
        getContentPane().add(jLImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtContrasenaActionPerformed

    private void jBInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInicioActionPerformed
        // TODO add your handling code here:
        Principal p = Controlador.getCtr().getPrincipal();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    
          /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */  
    /*
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesion().setVisible(true);
            }
        });
    }
   //</editor-fold>

        /* Create and display the form */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBInicio;
    private javax.swing.JButton jLConfirmar;
    private javax.swing.JLabel jLContrasena;
    private javax.swing.JLabel jLImagen;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jtContrasena;
    // End of variables declaration//GEN-END:variables
}
