/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Controlador;
import java.awt.Image;
import java.awt.Toolkit;


/**
 *
 * @author danip
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public Principal() {
         
        initComponents();
        setIconImage(getIconImage());
        this.setLocationRelativeTo(null);
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Resources/icons2.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBMEnu = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jBIniciarSesion = new javax.swing.JButton();
        jBRegistrarse = new javax.swing.JButton();
        lblUp = new javax.swing.JLabel();
        jLImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");
        setMaximumSize(new java.awt.Dimension(760, 505));
        setMinimumSize(new java.awt.Dimension(760, 505));
        setPreferredSize(new java.awt.Dimension(760, 505));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBMEnu.setBackground(new java.awt.Color(241, 234, 226));
        jBMEnu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBMEnu.setForeground(new java.awt.Color(89, 17, 18));
        jBMEnu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/resMenu.png"))); // NOI18N
        jBMEnu.setText("Ver Menú");
        jBMEnu.setMaximumSize(new java.awt.Dimension(130, 40));
        jBMEnu.setMinimumSize(new java.awt.Dimension(130, 40));
        jBMEnu.setOpaque(false);
        jBMEnu.setPreferredSize(new java.awt.Dimension(130, 40));
        jBMEnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMEnuActionPerformed(evt);
            }
        });
        getContentPane().add(jBMEnu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 160, 40));

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 56)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(241, 234, 226));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTitulo.setText("Sunshine ");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 390, -1));

        jBIniciarSesion.setBackground(new java.awt.Color(241, 234, 226));
        jBIniciarSesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBIniciarSesion.setForeground(new java.awt.Color(89, 17, 18));
        jBIniciarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/iniSecc.png"))); // NOI18N
        jBIniciarSesion.setText("IniciarSesion");
        jBIniciarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBIniciarSesion.setMaximumSize(new java.awt.Dimension(130, 40));
        jBIniciarSesion.setMinimumSize(new java.awt.Dimension(130, 40));
        jBIniciarSesion.setOpaque(false);
        jBIniciarSesion.setPreferredSize(new java.awt.Dimension(130, 40));
        jBIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIniciarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(jBIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 160, -1));

        jBRegistrarse.setBackground(new java.awt.Color(241, 234, 226));
        jBRegistrarse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBRegistrarse.setForeground(new java.awt.Color(89, 17, 18));
        jBRegistrarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/addUser.png"))); // NOI18N
        jBRegistrarse.setText("Registrarse");
        jBRegistrarse.setMaximumSize(new java.awt.Dimension(130, 40));
        jBRegistrarse.setMinimumSize(new java.awt.Dimension(130, 40));
        jBRegistrarse.setOpaque(false);
        jBRegistrarse.setPreferredSize(new java.awt.Dimension(130, 40));
        jBRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarseActionPerformed(evt);
            }
        });
        getContentPane().add(jBRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 160, -1));

        lblUp.setBackground(new java.awt.Color(255, 235, 238));
        lblUp.setOpaque(true);
        getContentPane().add(lblUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 60));

        jLImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/background-150p-01.jpg"))); // NOI18N
        jLImagen.setMaximumSize(new java.awt.Dimension(760, 505));
        jLImagen.setMinimumSize(new java.awt.Dimension(760, 505));
        jLImagen.setPreferredSize(new java.awt.Dimension(760, 505));
        getContentPane().add(jLImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 790, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBMEnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMEnuActionPerformed
        // TODO add your handling code here:
        VerMenu vm = Controlador.getCtr().getVerMenu();
        vm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBMEnuActionPerformed

    private void jBRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrarseActionPerformed
        // TODO add your handling code here:
        Registrarse r = Controlador.getCtr().getRegistrarse();
        r.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jBRegistrarseActionPerformed

    private void jBIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIniciarSesionActionPerformed
        // TODO add your handling code here:
        IniciarSesion is = Controlador.getCtr().getIniciarSesion();
        is.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBIniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBIniciarSesion;
    private javax.swing.JButton jBMEnu;
    private javax.swing.JButton jBRegistrarse;
    private javax.swing.JLabel jLImagen;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel lblUp;
    // End of variables declaration//GEN-END:variables
}
