/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Controlador;
import Model.UserClient;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/** 
 *
 * @author danip
 */
public class Registrarse extends javax.swing.JFrame {

    /**
     * Creates new form Registrarse
     */
    public Registrarse() {
        initComponents();
        setIconImage(getIconImage());
        this.setLocationRelativeTo(null);
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Resources/icons2.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBInicio = new javax.swing.JButton();
        jBConfirmar = new javax.swing.JButton();
        jLTitulo = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jLContrasena = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jTContrasena = new javax.swing.JTextField();
        jTConfirmacionContrasena = new javax.swing.JTextField();
        jLConfirmacionContrasena = new javax.swing.JLabel();
        lblUp = new javax.swing.JLabel();
        lblDataSesion = new javax.swing.JLabel();
        lblDataSesion1 = new javax.swing.JLabel();
        jLImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");
        setMaximumSize(new java.awt.Dimension(760, 505));
        setMinimumSize(new java.awt.Dimension(760, 505));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBInicio.setBackground(new java.awt.Color(241, 234, 226));
        jBInicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBInicio.setForeground(new java.awt.Color(89, 17, 18));
        jBInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/menuPrin.png"))); // NOI18N
        jBInicio.setText("Inicio");
        jBInicio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jBInicio.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jBInicio.setMaximumSize(new java.awt.Dimension(130, 40));
        jBInicio.setMinimumSize(new java.awt.Dimension(130, 40));
        jBInicio.setOpaque(false);
        jBInicio.setPreferredSize(new java.awt.Dimension(130, 40));
        jBInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInicioActionPerformed(evt);
            }
        });
        getContentPane().add(jBInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 140, -1));

        jBConfirmar.setBackground(new java.awt.Color(241, 234, 226));
        jBConfirmar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBConfirmar.setForeground(new java.awt.Color(89, 17, 18));
        jBConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/checked2.png"))); // NOI18N
        jBConfirmar.setText("Confirmar   ");
        jBConfirmar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jBConfirmar.setMaximumSize(new java.awt.Dimension(130, 40));
        jBConfirmar.setMinimumSize(new java.awt.Dimension(130, 40));
        jBConfirmar.setOpaque(false);
        jBConfirmar.setPreferredSize(new java.awt.Dimension(130, 40));
        jBConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(jBConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 200, -1));

        jLTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(241, 234, 226));
        jLTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTitulo.setText("Realizar Registro");
        getContentPane().add(jLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 510, -1));

        jLNombre.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(241, 234, 226));
        jLNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLNombre.setText("Nombre:");
        getContentPane().add(jLNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 230, -1));

        jLContrasena.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLContrasena.setForeground(new java.awt.Color(241, 234, 226));
        jLContrasena.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLContrasena.setText("Contraseña:");
        getContentPane().add(jLContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 230, -1));

        jTNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 200, -1));

        jTContrasena.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTContrasenaActionPerformed(evt);
            }
        });
        getContentPane().add(jTContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 200, -1));

        jTConfirmacionContrasena.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTConfirmacionContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTConfirmacionContrasenaActionPerformed(evt);
            }
        });
        getContentPane().add(jTConfirmacionContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 200, -1));

        jLConfirmacionContrasena.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLConfirmacionContrasena.setForeground(new java.awt.Color(241, 234, 226));
        jLConfirmacionContrasena.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLConfirmacionContrasena.setText("Confirmar Contraseña:");
        getContentPane().add(jLConfirmacionContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 230, 30));

        lblUp.setBackground(new java.awt.Color(255, 235, 238));
        lblUp.setOpaque(true);
        getContentPane().add(lblUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 60));

        lblDataSesion.setBackground(new java.awt.Color(167, 39, 32));
        lblDataSesion.setOpaque(true);
        getContentPane().add(lblDataSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 510, 330));

        lblDataSesion1.setBackground(new java.awt.Color(98, 39, 32));
        lblDataSesion1.setOpaque(true);
        getContentPane().add(lblDataSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 510, 330));

        jLImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/vinoConBlanco.jpg"))); // NOI18N
        jLImagen.setMaximumSize(new java.awt.Dimension(760, 505));
        jLImagen.setMinimumSize(new java.awt.Dimension(760, 505));
        jLImagen.setPreferredSize(new java.awt.Dimension(760, 505));
        getContentPane().add(jLImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNombreActionPerformed

    private void jTConfirmacionContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTConfirmacionContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTConfirmacionContrasenaActionPerformed

    private void jTContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTContrasenaActionPerformed

    private void jBInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInicioActionPerformed
        // TODO add your handling code here:
        Principal p = Controlador.getCtr().getPrincipal();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBInicioActionPerformed

    private void jBConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmarActionPerformed
        // TODO add your handling code here:
        addNuevoUser();
    }//GEN-LAST:event_jBConfirmarActionPerformed

    private void addNuevoUser(){
        if(validarCampos()){
          String mensaje = Controlador.getCtr().setNewUsersClient(new UserClient(this.jTNombre.getText(),
                  this.jTContrasena.getText(),0));
          Controlador.getCtr().setUsersArray();
          JOptionPane.showMessageDialog(null,mensaje);
          limpiarCampos();
        }else{
          JOptionPane.showMessageDialog(null, "Llene los datos correspondientes");
        }

    }
    
    private void limpiarCampos(){
         this.jTNombre.setText("");
         this.jTContrasena.setText("");
         this.jTConfirmacionContrasena.setText("");
    }
    
    private boolean validarCampos(){
        boolean result = true;
        if(this.jTNombre.getText().isEmpty() || this.jTContrasena.getText().isEmpty() 
                || this.jTConfirmacionContrasena.getText().isEmpty()
                ||!(this.jTContrasena.getText().equals(this.jTConfirmacionContrasena.getText())))
            result = false;
        return result;
    }
    /**
     * @param args the command line arguments
     */
    
            /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    /*
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrarse().setVisible(true);
            }
        });
    }
            //</editor-fold>

        /* Create and display the form */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConfirmar;
    private javax.swing.JButton jBInicio;
    private javax.swing.JLabel jLConfirmacionContrasena;
    private javax.swing.JLabel jLContrasena;
    private javax.swing.JLabel jLImagen;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JTextField jTConfirmacionContrasena;
    private javax.swing.JTextField jTContrasena;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JLabel lblDataSesion;
    private javax.swing.JLabel lblDataSesion1;
    private javax.swing.JLabel lblUp;
    // End of variables declaration//GEN-END:variables
}
