/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Controlador;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author danip
 */
public class Registrarse extends javax.swing.JFrame {

    /**
     * Creates new form Registrarse
     */
    public Registrarse() {
        initComponents();
        setIconImage(getIconImage());
        this.setLocationRelativeTo(null);
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Resources/icons2.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBInicio = new javax.swing.JButton();
        jBConfirmar = new javax.swing.JButton();
        jLTitulo = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jLContrasena = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jTContrasena = new javax.swing.JTextField();
        jTConfirmacionContrasena = new javax.swing.JTextField();
        jLConfirmacionContrasena = new javax.swing.JLabel();
        jLImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(760, 505));
        setMinimumSize(new java.awt.Dimension(760, 505));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBInicio.setBackground(new java.awt.Color(241, 234, 226));
        jBInicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBInicio.setForeground(new java.awt.Color(89, 17, 18));
        jBInicio.setText("Inicio");
        jBInicio.setMaximumSize(new java.awt.Dimension(130, 40));
        jBInicio.setMinimumSize(new java.awt.Dimension(130, 40));
        jBInicio.setPreferredSize(new java.awt.Dimension(130, 40));
        jBInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInicioActionPerformed(evt);
            }
        });
        getContentPane().add(jBInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, -1));

        jBConfirmar.setBackground(new java.awt.Color(241, 234, 226));
        jBConfirmar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBConfirmar.setForeground(new java.awt.Color(89, 17, 18));
        jBConfirmar.setText("Confirmar");
        jBConfirmar.setMaximumSize(new java.awt.Dimension(130, 40));
        jBConfirmar.setMinimumSize(new java.awt.Dimension(130, 40));
        jBConfirmar.setPreferredSize(new java.awt.Dimension(130, 40));
        getContentPane().add(jBConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, -1, -1));

        jLTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(241, 234, 226));
        jLTitulo.setText("Realizar Registro");
        getContentPane().add(jLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        jLNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(241, 234, 226));
        jLNombre.setText("Nombre");
        getContentPane().add(jLNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        jLContrasena.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLContrasena.setForeground(new java.awt.Color(241, 234, 226));
        jLContrasena.setText("Contraseña");
        getContentPane().add(jLContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        jTNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 160, -1));

        jTContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTContrasenaActionPerformed(evt);
            }
        });
        getContentPane().add(jTContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 160, -1));

        jTConfirmacionContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTConfirmacionContrasenaActionPerformed(evt);
            }
        });
        getContentPane().add(jTConfirmacionContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 160, -1));

        jLConfirmacionContrasena.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLConfirmacionContrasena.setForeground(new java.awt.Color(241, 234, 226));
        jLConfirmacionContrasena.setText("Confirmar Contraseña");
        getContentPane().add(jLConfirmacionContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        jLImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/vinoConBlanco.jpg"))); // NOI18N
        jLImagen.setMaximumSize(new java.awt.Dimension(760, 505));
        jLImagen.setMinimumSize(new java.awt.Dimension(760, 505));
        jLImagen.setPreferredSize(new java.awt.Dimension(760, 505));
        getContentPane().add(jLImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNombreActionPerformed

    private void jTConfirmacionContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTConfirmacionContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTConfirmacionContrasenaActionPerformed

    private void jTContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTContrasenaActionPerformed

    private void jBInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInicioActionPerformed
        // TODO add your handling code here:
        Principal p = Controlador.getCtr().getPrincipal();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    
            /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    /*
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrarse().setVisible(true);
            }
        });
    }
            //</editor-fold>

        /* Create and display the form */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConfirmar;
    private javax.swing.JButton jBInicio;
    private javax.swing.JLabel jLConfirmacionContrasena;
    private javax.swing.JLabel jLContrasena;
    private javax.swing.JLabel jLImagen;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JTextField jTConfirmacionContrasena;
    private javax.swing.JTextField jTContrasena;
    private javax.swing.JTextField jTNombre;
    // End of variables declaration//GEN-END:variables
}
