/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Controlador;
import javax.swing.JPanel;

/**
 * 
 * @author danip
 */
public class VentanaGerente extends javax.swing.JFrame {

    /**
     * Creates new form VentanaGerente
     */
    public VentanaGerente() {
        initComponents();
        
    }

    public JPanel getjPGerenteGeneral() {
        return jPGerenteGeneral;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTitulo = new javax.swing.JLabel();
        jBInicio = new javax.swing.JButton();
        jBReportePorSucursal = new javax.swing.JButton();
        jPGerenteGeneral = new javax.swing.JPanel();
        jBVerReporteMensual = new javax.swing.JButton();
        jBVerReporteGeneral = new javax.swing.JButton();
        jBAgregarProducto = new javax.swing.JButton();
        jBEditarMenu = new javax.swing.JButton();
        jBEditarCombos = new javax.swing.JButton();
        jBVerListaEmpleados = new javax.swing.JButton();
        jLImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(760, 505));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTitulo.setBackground(new java.awt.Color(241, 234, 226));
        jLTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(241, 234, 226));
        jLTitulo.setText("Opciones de Gerencia ");
        getContentPane().add(jLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 440, 60));

        jBInicio.setBackground(new java.awt.Color(241, 234, 226));
        jBInicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBInicio.setText("Inicio");
        getContentPane().add(jBInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 100, 40));

        jBReportePorSucursal.setBackground(new java.awt.Color(241, 234, 226));
        jBReportePorSucursal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBReportePorSucursal.setForeground(new java.awt.Color(89, 17, 18));
        jBReportePorSucursal.setText("Reporte de Sucursal");
        jBReportePorSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReportePorSucursalActionPerformed(evt);
            }
        });
        getContentPane().add(jBReportePorSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 190, -1));

        jPGerenteGeneral.setBackground(new java.awt.Color(89, 17, 18));
        jPGerenteGeneral.setForeground(new java.awt.Color(89, 17, 18));

        jBVerReporteMensual.setBackground(new java.awt.Color(241, 234, 226));
        jBVerReporteMensual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBVerReporteMensual.setForeground(new java.awt.Color(89, 17, 18));
        jBVerReporteMensual.setText("Reporte Mensual");
        jBVerReporteMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVerReporteMensualActionPerformed(evt);
            }
        });

        jBVerReporteGeneral.setBackground(new java.awt.Color(241, 234, 226));
        jBVerReporteGeneral.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBVerReporteGeneral.setForeground(new java.awt.Color(89, 17, 18));
        jBVerReporteGeneral.setText("Ver Reporte General");
        jBVerReporteGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVerReporteGeneralActionPerformed(evt);
            }
        });

        jBAgregarProducto.setBackground(new java.awt.Color(241, 234, 226));
        jBAgregarProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBAgregarProducto.setForeground(new java.awt.Color(89, 17, 18));
        jBAgregarProducto.setText("Agregar Producto");
        jBAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarProductoActionPerformed(evt);
            }
        });

        jBEditarMenu.setBackground(new java.awt.Color(241, 234, 226));
        jBEditarMenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBEditarMenu.setForeground(new java.awt.Color(89, 17, 18));
        jBEditarMenu.setText("Editar Menu");
        jBEditarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarMenuActionPerformed(evt);
            }
        });

        jBEditarCombos.setBackground(new java.awt.Color(241, 234, 226));
        jBEditarCombos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBEditarCombos.setForeground(new java.awt.Color(89, 17, 18));
        jBEditarCombos.setText("Editar Combos");
        jBEditarCombos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarCombosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPGerenteGeneralLayout = new javax.swing.GroupLayout(jPGerenteGeneral);
        jPGerenteGeneral.setLayout(jPGerenteGeneralLayout);
        jPGerenteGeneralLayout.setHorizontalGroup(
            jPGerenteGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPGerenteGeneralLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(jPGerenteGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBVerReporteGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBVerReporteMensual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBAgregarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBEditarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBEditarCombos, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );
        jPGerenteGeneralLayout.setVerticalGroup(
            jPGerenteGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPGerenteGeneralLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jBVerReporteMensual)
                .addGap(18, 18, 18)
                .addComponent(jBVerReporteGeneral)
                .addGap(18, 18, 18)
                .addComponent(jBAgregarProducto)
                .addGap(18, 18, 18)
                .addComponent(jBEditarMenu)
                .addGap(18, 18, 18)
                .addComponent(jBEditarCombos)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        getContentPane().add(jPGerenteGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 310, 340));

        jBVerListaEmpleados.setBackground(new java.awt.Color(241, 234, 226));
        jBVerListaEmpleados.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBVerListaEmpleados.setForeground(new java.awt.Color(89, 17, 18));
        jBVerListaEmpleados.setText("Ver Lista de Empleados");
        jBVerListaEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVerListaEmpleadosActionPerformed(evt);
            }
        });
        getContentPane().add(jBVerListaEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        jLImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/vinoConBlanco.jpg"))); // NOI18N
        getContentPane().add(jLImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBEditarCombosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarCombosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jBEditarCombosActionPerformed

    private void jBVerReporteMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVerReporteMensualActionPerformed
        // TODO add your handling code here:
        Controlador.getCtr().getReportes().setVisible(true);
        Controlador.getCtr().getReportes().getjPSeleccionSucursal().setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jBVerReporteMensualActionPerformed

    private void jBReportePorSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReportePorSucursalActionPerformed
        // TODO add your handling code here:
        Controlador.getCtr().getReportes().setVisible(true);
        Controlador.getCtr().getReportes().getjPSeleccionSucursal().setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jBReportePorSucursalActionPerformed

    private void jBVerListaEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVerListaEmpleadosActionPerformed
        // TODO add your handling code here:
        //Controlador.getCtr().cargarDatosBase();
        Controlador.getCtr().getListaEmpleados().setVisible(true);
        this.dispose();
        Controlador.getCtr().verListaEmpleados();
    }//GEN-LAST:event_jBVerListaEmpleadosActionPerformed

    private void jBVerReporteGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVerReporteGeneralActionPerformed
        // TODO add your handling code here:
        Controlador.getCtr().getReportes().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBVerReporteGeneralActionPerformed

    private void jBAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarProductoActionPerformed
        // TODO add your handling code here:
        Controlador.getCtr().getAgregarProducto();
        this.dispose();
    }//GEN-LAST:event_jBAgregarProductoActionPerformed

    private void jBEditarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarMenuActionPerformed
        // TODO add your handling code here:
        Controlador.getCtr().getEditarMEnu();
        this.dispose();
    }//GEN-LAST:event_jBEditarMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregarProducto;
    private javax.swing.JButton jBEditarCombos;
    private javax.swing.JButton jBEditarMenu;
    private javax.swing.JButton jBInicio;
    private javax.swing.JButton jBReportePorSucursal;
    private javax.swing.JButton jBVerListaEmpleados;
    private javax.swing.JButton jBVerReporteGeneral;
    private javax.swing.JButton jBVerReporteMensual;
    private javax.swing.JLabel jLImagen;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JPanel jPGerenteGeneral;
    // End of variables declaration//GEN-END:variables
}
