/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Controlador;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author danip
 */
public class VerMenu extends javax.swing.JFrame {

    /**
     * Creates new form VerMenu
     */
    public VerMenu() {
        initComponents();
        setIconImage(getIconImage());
        this.setLocationRelativeTo(null);
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Resources/icons2.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBCombos = new javax.swing.JButton();
        jBPostres = new javax.swing.JButton();
        jBBebidas = new javax.swing.JButton();
        jBComidas = new javax.swing.JButton();
        jBInicio = new javax.swing.JButton();
        jPProductos = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jLImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(760, 505));
        setMinimumSize(new java.awt.Dimension(760, 505));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBCombos.setBackground(new java.awt.Color(241, 234, 226));
        jBCombos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBCombos.setForeground(new java.awt.Color(89, 17, 18));
        jBCombos.setText("Combos");
        jBCombos.setMaximumSize(new java.awt.Dimension(130, 40));
        jBCombos.setMinimumSize(new java.awt.Dimension(130, 40));
        jBCombos.setPreferredSize(new java.awt.Dimension(130, 40));
        getContentPane().add(jBCombos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jBPostres.setBackground(new java.awt.Color(241, 234, 226));
        jBPostres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBPostres.setForeground(new java.awt.Color(89, 17, 18));
        jBPostres.setText("Postres");
        jBPostres.setMaximumSize(new java.awt.Dimension(130, 40));
        jBPostres.setMinimumSize(new java.awt.Dimension(130, 40));
        jBPostres.setPreferredSize(new java.awt.Dimension(130, 40));
        getContentPane().add(jBPostres, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jBBebidas.setBackground(new java.awt.Color(241, 234, 226));
        jBBebidas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBBebidas.setForeground(new java.awt.Color(89, 17, 18));
        jBBebidas.setText("Bebidas");
        jBBebidas.setMaximumSize(new java.awt.Dimension(130, 40));
        jBBebidas.setMinimumSize(new java.awt.Dimension(130, 40));
        jBBebidas.setPreferredSize(new java.awt.Dimension(130, 40));
        getContentPane().add(jBBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jBComidas.setBackground(new java.awt.Color(241, 234, 226));
        jBComidas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBComidas.setForeground(new java.awt.Color(89, 17, 18));
        jBComidas.setText("Comidas");
        jBComidas.setMaximumSize(new java.awt.Dimension(130, 40));
        jBComidas.setMinimumSize(new java.awt.Dimension(130, 40));
        jBComidas.setPreferredSize(new java.awt.Dimension(130, 40));
        getContentPane().add(jBComidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        jBInicio.setBackground(new java.awt.Color(241, 234, 226));
        jBInicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBInicio.setForeground(new java.awt.Color(89, 17, 18));
        jBInicio.setText("Inicio");
        jBInicio.setMaximumSize(new java.awt.Dimension(130, 40));
        jBInicio.setMinimumSize(new java.awt.Dimension(130, 40));
        jBInicio.setPreferredSize(new java.awt.Dimension(130, 40));
        jBInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInicioActionPerformed(evt);
            }
        });
        getContentPane().add(jBInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jPProductos.setViewportView(jTableProductos);

        getContentPane().add(jPProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, 360));

        jLImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/vinoConBlanco.jpg"))); // NOI18N
        jLImagen.setMaximumSize(new java.awt.Dimension(760, 505));
        jLImagen.setMinimumSize(new java.awt.Dimension(760, 505));
        jLImagen.setPreferredSize(new java.awt.Dimension(760, 505));
        getContentPane().add(jLImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInicioActionPerformed
        // TODO add your handling code here:
        Principal p = Controlador.getCtr().getPrincipal();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    
            /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    /*
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerMenu().setVisible(true);
            }
        });
    }
    /* Create and display the form */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBebidas;
    private javax.swing.JButton jBCombos;
    private javax.swing.JButton jBComidas;
    private javax.swing.JButton jBInicio;
    private javax.swing.JButton jBPostres;
    private javax.swing.JLabel jLImagen;
    private javax.swing.JScrollPane jPProductos;
    private javax.swing.JTable jTableProductos;
    // End of variables declaration//GEN-END:variables
}
